const types = {
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_FINISHED: 'SIGNUP_FINISHED',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    LOGIN_START: 'LOGIN_START',
    LOGIN_FINISHED: 'LOGIN_FINISHED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_FINISHED: 'LOGOUT_FINISHED',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
    GET_USER_START: 'GET_USER_START',
    GET_USER_FINISHED: 'GET_USER_FINISHED',
    GET_USER_ERROR: 'GET_USER_ERROR',
    SET_USER: 'SET_USER',
    CLEAR_STORE: 'CLEAR_STORE'
};

export default types;
