# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'animations' do
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Core'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for animations

  target 'animationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'animations-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for animations-tvOS

  target 'animations-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
